### ISSUE TITLE
Navigations rings ative search when not configured

### ISSUE THREAD

**Issue by dcop7** [Euphoria-OS/Bug-tracker#1] opened 2015-05-11 18:43 UTC
Do you use Xposed framework? No.

Your device: Nexus 4

Which ROM version are you using? Euphoria-OS-1.1-mako-20150428.zip

What kernel are you using - included in the ROM or from another source? Hellscore b75

What steps will reproduce the problem?
1. Set only the middle nagivation ring to screen off, leaving the left and right navigation not defined
2. Activate the navigation rings and release the finger on the left or right navigation.

What is the expected result? What do you see instead?
Instead of activate the only ring configured, it opens the search.

Is the result seen after a clean flash too?
Yes.

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.
I don't think a logcat will help, since it is not an error per se.
If needed, I will post one.

**Comment by dexmc** [comment] 2015-05-12 05:28
@dcop7  We can confirm this, but isn't this stock behavior? You swipe the empty area around the ring and it always opens Gsearch.

**Comment by dexmc** [comment] 2015-05-12 05:33
@dcop7  also the option does not say Disable, only says "None" which means it will default to stock behavior. 

Also, if you want, you could go ahead and disable the rings. I think I'm closing this one, after Altaf shares his thoughts on this.

**Comment by mitchelldavis44** [comment] 2015-05-12 05:40
Confirmed on stock 5.1.1, this is default behavior.  Stock behavior when swiping up from home button animates the Google "fab" and tells you it's going to open the search app.  Setting the other two rings to None is going to result in stock behavior, either set the other rings to something else or you will have to take your finger off the home button and don't swipe up.  +1, not a bug.

**Comment by dcop7** [comment] 2015-05-13 12:53
In Euphoria 1 (5.0) it worked like I described that how it should work. Now, with Euphoria 1.1 (5.1.1), it changed. Why the change? That is why I think it is a bug.

But if I set a navigation ring to "none", it should be none, not the stock behavior. If I want to change the navigation ring to search, I set to search, not to none.

**Comment by mitchelldavis44** [comment] 2015-05-14 10:32
I don't ever remember it working the way you're describing.  Like I stated, it is supposed to open the google app, if you would like it to _not_ then that's more of a "feature" request and not a bug.  If you set it to none it's only implying that you are not setting another target and so it will revert back to using the Google app as it's target, this is the way Lollipop is written.

**Closed as completed** 2015-05-17 10:22 UTC
Labels: invalid, nexus4
