### ISSUE TITLE
QS Task manager bug

### ISSUE THREAD

**Issue by arvind-gr** [Euphoria-OS/Bug-tracker#18] opened 2015-06-14 09:28 UTC
After Opening task manager, I swipe from bottom to exit it. But next time I open Notification, task manger comes open. Only way to exit it is, I need to press QS icon to exit it. Pressing back is not option there. Consider fixing it...

Device details.,  
Euphoria Mako latest 13062015 built with Quanto kernel

**Comment by dexmc** [comment] 2015-06-16 16:07
its not a bug. its a feature!
There just isnt an option to close it properly. Its being worked on.

**Closed as completed** 2015-07-02 16:56 UTC
Labels: enhancement, feature-request
